
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Grad School Application Guide
author: "Westley Weimer"
author2: "Madeline Endres"
email: wiemerw@umich.edu
email2: mendres@umass.edu
description: >- # this means to ignore newlines until "baseurl:"
  A resource for applying to graduate school
baseurl: "/grad-school-application-guide" # the subpath of your site, e.g. /blog
url: "https://csguides.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
github_username: 
# google_analytics: G-PNQ65W15RF # kevin's
# google_analytics: G-V6DRFB5162 # Maddy's

repo: 
comments: false

header_pages:
  - index.md
  - why-apply.md
  - evaluations.md
  - applying.md
  - interviewing.md
  - deciding.md
  - misc.md
  - life-grad-school.md
  - exampleMaterials.md
  - about.md

footer_pages:
  - about.md
    
# Build settings
plugins:
  - jeckyll-last-modified-at
  - jekyll-sitemap

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
